#' Generate the CHL 26 Predictor Scores
#'
#' \code{get_CHL26_score} returns the CHL26 score 
#'
#' @param mat.norm Normalized expression matrix generated by 
#'   \code{normalizer_mat}
#' @return A numeric vector with the colnames of mat.norm as keys and scores as
#'   values.
#' @export
#' @examples
#' normalizer <- get_normalizer(mat)
#' mat.norm <- normalize_mat(mat, normalizer)
#' get_CHL26_scores(mat.norm)
get_CHL26_scores <- function(mat.norm) {

  if (!all(CHL26.model.coef.df$geneName %in% rownames(mat))) {
    missing.gene <- !CHL26.model.coef.df$geneName %in% rownames(mat)
    stop(paste("Following genes missing from gene expression matrix:", 
               paste(CHL26.model.coef.df[missing.gene, "geneName"], collapse = ", ")
               )
    )
  }

  model.coef <- matrix(CHL26.model.coef.df$coef, 1, nrow(CHL26.model.coef.df),
                       dimnames = list(NULL, CHL26.model.coef.df$geneName))
  scores <- model.coef %*% mat.norm[colnames(model.coef), ]
  scores.vector <- scores[1, ]
  scores.vector
}
