#' Generate the Normalizer Values for each Sample
#'
#' \code{get_normalizer} returns the normalizer values for each sample. The 
#' normalizer value is based on the geometric mean of the housekeeper genes
#' ACTB, CLTC, and RPLP0
#'
#' @param mat The expression matrix
#' @return A numeric vector with the samples as names and the normalizer 
#'   as values
#' @examples
#' normalizer <- get_normalizer(mat)
get_normalizer <- function(mat) {
  message("Generating the geometric mean of housekeeper genes")
  genes.norm.factor <- c("ACTB", "CLTC", "RPLP0")

  normalizer.log <- log(mat[genes.norm.factor, ])
  normalizer.log.mean <- apply(normalizer.log, 2, mean)
  normalizer.log.mean.exp <- exp(normalizer.log.mean)
  normalizer.log.mean.exp
}

#' Normalize the Expression Matrix 
#'
#' This function normalizes the expression matrix.
#' 
#' @param mat The expression matrix
#' @param normalizer Normalizer values generated by \code{get_normalizer}
#' @return A normalized expression matrix
#' @export
#' @examples
#' normalizer <- get_normalizer(mat)
#' mat.norm <- normalizer_mat(mat, normalizer)
normalize_mat <- function(mat, normalizer) {

  message("Normalizing the expression matrix")
  mat.norm <- sweep(mat, 2, normalizer, "/")
  mat.norm.scaled <- mat.norm * 1000

  # Ensure that any values < 1 do not become negative
  mat.norm.scaled[mat.norm.scaled < 1] <- 1

  message("Log2 transforming")
  mat.norm.scaled.log <- log(mat.norm.scaled, 2)
  mat.norm.scaled.log
} 
